# ----
# Site

title: NixPen 5.0
url: "https://namin01379.github.io/sample_origin/"
baseurl:
google_analytics_key:
show_full_navigation: true

# 추적 ID 입력
google_analytics_id: UA-80265650-1

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release
